name: Waka Readme

on:

  schedule:

    # Runs every 4 hours

    - cron: '0 */8 * * *'

  workflow_dispatch:

jobs:

  update-readme:
 
    name: Update Readme with Metrics

    runs-on: ubuntu-latest

    steps:

      #- uses: actions/checkout@v3
      - uses: dmighty007/dmighty007@main

        with:

          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true

